channel_sources:
  - deepmodeling,https://deepmodeling.njzjz.win,defaults,conda-forge # [linux-64]
  - deepmodeling,https://deepmodeling.njzjz.win,defaults,conda-forge # [ppc64le]
dp_variant:
  - cpu
  - gpu
