{% set name = "openmm_deepmd_plugin" %}
{% set version = "2.0.0" %}
{% set cuda_compiler_version = "10.1" %}
{% set dp_variant = "gpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/JingHuangLab/openmm_deepmd_plugin.git
  git_rev: 9ba5f5268a48557d59cf976574ef514c80cf80c2
  patches:
    - cuda_platform.patch

build:
  number: 1
  string: "{{ PKG_BUILDNUM }}_cuda{{ cuda_compiler_version }}_{{ dp_variant }}" 
  skip: True  # [not linux]
  missing_dso_whitelist:
    - "*/libcuda.*"    # [linux64 or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17 # [linux64]
    - cython
    - cmake
    - make
    - numpy
    - cython
    - swig

  host:
    - python  # [not ppc64le]
    - cudatoolkit {{ cuda_compiler_version }}*
    - libdeepmd {{ version }} *gpu
    - openmm 7.6
    - fftw
    - numpy
    - cython
    - swig

  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [cuda_compiler_version != 'None']
    - python 
    - libdeepmd >={{ version }} *gpu
    - fftw
    - openmm 7.6
    - numpy
    - cython
    - swig

test:
  commands:
    - python -m openmm.testInstallation
    - test -f $PREFIX/lib/libOpenMM.so
    - test -f $PREFIX/lib/libOpenMMDeepmd.so
    - python -m OpenMMDeepmdPluginTools.test_dp_plugin_nve

about:
  home: https://github.com/JingHuangLab/openmm_deepmd_plugin.git
  summary: 'OpenMM Plugin for Deepmd-kit.'
  license: LGPL-3.0-or-later
  license_family: LGPL
  description: |
    OpenMM is a toolkit for molecular simulation. It can be used either as a
    stand-alone application for running simulations, or as a library you call
    from your own code. It provides a combination of extreme flexibility
    (through custom forces and integrators), openness, and high performance
    (especially on recent GPUs) that make it truly unique among simulation
    codes. OpenMM is MIT licensed with some LGPL portions (CUDA and OpenCL
    platforms).
  doc_url: http://docs.openmm.org
  dev_url: https://github.com/JingHuangLab/openmm_deepmd_plugin.git

extra:
  recipe-maintainers:
    - ye-ding
