{% set name = "openmm_deepmd_plugin" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/JingHuangLab/openmm_deepmd_plugin.git
  git_rev: 857eec25c892f3d9fa9ddd1479d1a484a67cc1d9
  patches:
    - cuda_platform.patch

build:
  number: 0
  skip: True  # [not linux]
  missing_dso_whitelist:
    - "*/libcuda.*"    # [linux64 or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17 # [linux64]
    - cmake
    - make
    - swig

  host:
    - python  # [not ppc64le]
    - libdeepmd {{ version }} *_{{ dp_variant }}
    - cudatoolkit >=10  # [dp_variant != 'cpu']
    - openmm 7.6
    - fftw
    - numpy
    - cython
    - swig

  run:
    - python 
    - libdeepmd >={{ version }} *_{{ dp_variant }}
    - cudatoolkit >=10  # [dp_variant != 'cpu']
    - fftw
    - openmm 7.6
    - numpy

test:
  commands:
    - python -m openmm.testInstallation
    - test -f $PREFIX/lib/libOpenMM.so
    - test -f $PREFIX/lib/libOpenMMDeepmd.so
    - python -m OpenMMDeepmdPluginTools.test_dp_plugin_nve

about:
  home: https://github.com/JingHuangLab/openmm_deepmd_plugin.git
  summary: 'OpenMM Plugin for Deepmd-kit.'
  license: LGPL-3.0-or-later
  license_family: LGPL
  description: |
    OpenMM is a toolkit for molecular simulation. It can be used either as a
    stand-alone application for running simulations, or as a library you call
    from your own code. It provides a combination of extreme flexibility
    (through custom forces and integrators), openness, and high performance
    (especially on recent GPUs) that make it truly unique among simulation
    codes. OpenMM is MIT licensed with some LGPL portions (CUDA and OpenCL
    platforms).
  doc_url: http://docs.openmm.org
  dev_url: https://github.com/JingHuangLab/openmm_deepmd_plugin.git

extra:
  recipe-maintainers:
    - ye-ding
